// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWzNFQwPGocwLnh533RCOgDaB8JT2aUxQ',
    appId: '1:553853711024:web:07f94e3dc57ca7a60dc175',
    messagingSenderId: '553853711024',
    projectId: 'bakeryapp-66a67',
    authDomain: 'bakeryapp-66a67.firebaseapp.com',
    storageBucket: 'bakeryapp-66a67.firebasestorage.app',
    measurementId: 'G-X3MK7ZMYDJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDa-O3HsfRT6KdfYI9XU4EMZY5141ARACI',
    appId: '1:553853711024:android:d132db37aa7b8b190dc175',
    messagingSenderId: '553853711024',
    projectId: 'bakeryapp-66a67',
    storageBucket: 'bakeryapp-66a67.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChzkwNtcnPEuuCBy0kmRXI7RRTC5VZD0A',
    appId: '1:553853711024:ios:7b5915350c75bad50dc175',
    messagingSenderId: '553853711024',
    projectId: 'bakeryapp-66a67',
    storageBucket: 'bakeryapp-66a67.firebasestorage.app',
    iosBundleId: 'com.example.bakeryAppCassielMariana',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChzkwNtcnPEuuCBy0kmRXI7RRTC5VZD0A',
    appId: '1:553853711024:ios:7b5915350c75bad50dc175',
    messagingSenderId: '553853711024',
    projectId: 'bakeryapp-66a67',
    storageBucket: 'bakeryapp-66a67.firebasestorage.app',
    iosBundleId: 'com.example.bakeryAppCassielMariana',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWzNFQwPGocwLnh533RCOgDaB8JT2aUxQ',
    appId: '1:553853711024:web:cc2499baff9e8f690dc175',
    messagingSenderId: '553853711024',
    projectId: 'bakeryapp-66a67',
    authDomain: 'bakeryapp-66a67.firebaseapp.com',
    storageBucket: 'bakeryapp-66a67.firebasestorage.app',
    measurementId: 'G-ED4HGHVJCH',
  );
}
